OperasWebSites/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OperasWebSites.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            return View("Index");
        }

        public ActionResult About()
        {
            return View("");
        }

        [HttpGet]
        public PartialViewResult _MyRefresh()
        {
            return PartialView("_MyRefresh");
        }

        public ContentResult getBackground()
        {
            string style;

            if(Session["BackgroundColor"] != null )
            {
                style = String.Format("background-color: {0}", Session["BackgroundColor"]);
            } else
            {
                style = "background-color: #dc9797";
            }

            return Content(style);
        }

        public ActionResult SetBackground(string color)
        {
            Session["BackgroundColor"] = color;
            return View("Index");
        }

    }
}

OperasWebSites/Controllers/OperaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using OperasWebSites.Models;
using System.Web.UI;
using OperasWebSites.GeocodeService;
using BingMapsRESTToolkit;

namespace OperasWebSites.Controllers
{
    public class OperaController : Controller
    {
        private OperasDB contextDB = new OperasDB();

        //
        // GET: /Opera/
        [OutputCache( Duration = 600, Location = OutputCacheLocation.Server, VaryByParam ="none")]
        public ActionResult Index()
        {
            return View("Index", contextDB.Operas.ToList());
        }

        public ActionResult Details(int id)
        {
            Opera opera = contextDB.Operas.Find(id);
            if (opera != null)
            {
                LocationCheckerServiceClient client = null;

                Location response = null;

                try
                {
                    client = new LocationCheckerServiceClient();
                    response = client.GetLocation("Copenhagen");

                    var coor = response.GeocodePoints.FirstOrDefault().GetCoordinate();

                    opera.GeocodeResult = "" + coor.Longitude +":" + coor.Latitude;

                }
                catch ( Exception e)
                {
                    opera.GeocodeResult = "Error: " + e.Message;
                }


                return View("Details", opera);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult DetailsByTitle(string title)
        {
            Opera opera = (Opera)(from o in contextDB.Operas
                                  where o.Title == title
                                  select o).FirstOrDefault();
            if (opera == null)
            {
                return HttpNotFound();
            }
            return View("Details", opera);
        }

        [Authorize]
        public ActionResult Create()
        {
            Opera newOpera = new Opera();
            return View("Create", newOpera);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(Opera newOpera)
        {
            if (ModelState.IsValid)
            {
                newOpera.CreatedBy = User.Identity.Name;
                contextDB.Operas.Add(newOpera);
                contextDB.SaveChanges();
                Response.RemoveOutputCacheItem(Url.Action("Index"));
                return RedirectToAction("Index");
            }
            else
            {
                return View("Create", newOpera);
            }
        }
    }
}

OperasWebSites/Views/Home/About.cshtml
@{
    ViewBag.Title = "About this site";
}

        <h1>
            About This Site
        </h1>
        <p>
            This is a site all about my hobby: watching operas.
        </p>

OperasWebSites/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<div>
    <p>
        Choose a background color:
        @Html.ActionLink("Pink", "SetBackground", new { color = "#dc9797" })
        @Html.ActionLink("Blue", "SetBackground", new { color = "#82bbf2" })
    </p>

    <h1>Operas I Have Seen</h1>

    <p>
        Welcome! On this site I'm going to discuss my hobby: listening
        to opera. Start by looking at the
        @Html.ActionLink("operas I've seen.", "Index", "Opera")
    </p>

    <div id="MyRefresh"></div>
    <input type="button" onclick="loadPartialView()" value="Refresh"/>
    <script>
        function loadPartialView() {
            $.ajax({
                url:      "@Url.Action("_MyRefresh", "Home")",
                type:     'GET',   // <-- make a async request by GET
                dataType: 'html' , // <-- to expect an html response
                success: function (result)
                {
                    $('#MyRefresh').html(result);
                }
            });
        }
        $(function () {

            loadPartialView(); // first time

            // re-call the function each 5 seconds
            window.setInterval("loadPartialView()", 10000);

        });
    </script>
</div>